replicaCount: 1

image:
  repository: docker.io/onurcetin/s4e-intern-devops
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
